### set_index()
- method used to set one or more columns of a dataframe as the index 
- useful when we need to modify or add new indices to our data as it enhances data retrieval indexing and merging tasks

In [3]:
import pandas as pd
data={'Name':["Alice","Bob","Charlie"],
     "Age":[25,30,35],
      "City":["NewYork","LosAngeles","Chicago"]}
df=pd.DataFrame(data)
df

      Name  Age        City
0    Alice   25     NewYork
1      Bob   30  LosAngeles
2  Charlie   35     Chicago

In [3]:
df.set_index('Name')

         Age        City
Name
Alice     25     NewYork
Bob       30  LosAngeles
Charlie   35     Chicago

In [4]:
df

      Name  Age        City
0    Alice   25     NewYork
1      Bob   30  LosAngeles
2  Charlie   35     Chicago

In [5]:
df.set_index('Name',drop=False)

            Name  Age        City
Name
Alice      Alice   25     NewYork
Bob          Bob   30  LosAngeles
Charlie  Charlie   35     Chicago

In [6]:
df

      Name  Age        City
0    Alice   25     NewYork
1      Bob   30  LosAngeles
2  Charlie   35     Chicago

In [4]:
df.set_index('Name',drop=False,inplace=True)# inplace update the dataframe

In [5]:
df

            Name  Age        City
Name
Alice      Alice   25     NewYork
Bob          Bob   30  LosAngeles
Charlie  Charlie   35     Chicago

In [6]:
df1=df.set_index('Name',drop=False)

In [7]:
df1

            Name  Age        City
Name
Alice      Alice   25     NewYork
Bob          Bob   30  LosAngeles
Charlie  Charlie   35     Chicago

### reset_index()
- used to manage and reset index of a dataframe

In [11]:
import pandas as pd
data={'Name':["Alice","Bob","Charlie"],
     "Age":[25,30,35],
      "City":["NewYork","LosAngeles","Chicago"]}
df=pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age        City
a    Alice   25     NewYork
b      Bob   30  LosAngeles
c  Charlie   35     Chicago

In [12]:
df_reset=df.reset_index()
df_reset

  index     Name  Age        City
0     a    Alice   25     NewYork
1     b      Bob   30  LosAngeles
2     c  Charlie   35     Chicago

In [13]:
df_reset=df.reset_index(drop=True)
df_reset

      Name  Age        City
0    Alice   25     NewYork
1      Bob   30  LosAngeles
2  Charlie   35     Chicago

In [14]:
import pandas as pd
data={'Name':["Alice","Bob","Charlie"],
     "Age":[25,30,35],
      "City":["NewYork","LosAngeles","Chicago"]}
df=pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age        City
a    Alice   25     NewYork
b      Bob   30  LosAngeles
c  Charlie   35     Chicago

In [17]:
df.sample()

    Name  Age     City
a  Alice   25  NewYork

In [18]:
data=[[10,20,0],[10,10,10],[10,20,30]]
df=pd.DataFrame(data)
df

    0   1   2
0  10  20   0
1  10  10  10
2  10  20  30

In [19]:
print(df.nunique())

0    1
1    2
2    3
dtype: int64

In [20]:
print(df.unique())

AttributeError: 'DataFrame' object has no attribute 'unique'

In [21]:
print(df[1].unique())

[20 10]

In [22]:
data={"Region":["North","North","South","South"],
     "City":["NewYork","LA","Miami","Houston"],
      "Population":[8.4,3.9,0.4,2.3]}
df=pd.DataFrame(data)
df

  Region     City  Population
0  North  NewYork         8.4
1  North       LA         3.9
2  South    Miami         0.4
3  South  Houston         2.3

In [23]:
print(df["Region"].unique())

['North' 'South']

In [24]:
print(df["City"].unique())

['NewYork' 'LA' 'Miami' 'Houston']

In [25]:
print(df.nunique())

Region        2
City          4
Population    4
dtype: int64

In [28]:
auto_mpg=pd.read_csv("auto-mpg.csv")
auto_mpg.info()
auto_mpg.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [30]:
auto_mpg[auto_mpg['horsepower']=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [32]:
auto_mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [33]:
auto_mpg[auto_mpg['horsepower'].isnull()]

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model year, origin, car name]
Index: []

In [34]:
auto_mpg.loc[5]

mpg                           15
cylinders                      8
displacement                 429
horsepower                   198
weight                      4341
acceleration                  10
model year                    70
origin                         1
car name        ford galaxie 500
Name: 5, dtype: object

In [35]:
auto_mpg.loc[5:10]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se

In [36]:
auto_mpg.iloc[5:10]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [37]:
auto_mpg['mpg']

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [38]:
auto_mpg['mpg'].loc[4]

17.0

In [41]:
auto_mpg.shape

(398, 9)

In [42]:
auto_mpg.shape[0]# it gives rows

398

In [43]:
auto_mpg.shape[1]#it gives columns

9

In [48]:
auto_mpg[auto_mpg['horsepower']=="?"].shape[0]

6

In [49]:
auto_mpg.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [ ]:
auto_mpg.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [52]:
import numpy as np
auto_mpg.describe(include=[np.number])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [53]:
auto_mpg.describe(exclude=[np.number])

       horsepower    car name
count         398         398
unique         94         305
top           150  ford pinto
freq           22           6

In [56]:
auto_mpg.describe(percentiles=[.40,.60,.80])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
40%,20.000000,4.000000,122.000000,2580.600000,14.800000,75.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
60%,25.000000,6.000000,200.000000,3085.200000,16.000000,77.000000,1.000000
80%,31.000000,8.000000,304.600000,3806.000000,17.760000,80.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [58]:
auto_mpg[['mpg','cylinders']].describe()

              mpg   cylinders
count  398.000000  398.000000
mean    23.514573    5.454774
std      7.815984    1.701004
min      9.000000    3.000000
25%     17.500000    4.000000
50%     23.000000    4.000000
75%     29.000000    8.000000
max     46.600000    8.000000

In [59]:
auto_mpg[0:50].describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,50.000000,50.000000,50.00000,50.000000,50.0000,50.000000,50.00000
mean,18.020000,6.480000,268.40000,3364.920000,13.5000,70.420000,1.26000
std,5.108976,1.693204,116.26553,901.242676,2.9277,0.498569,0.59966
min,9.000000,4.000000,97.00000,1835.000000,8.0000,70.000000,1.00000
25%,14.000000,4.500000,154.50000,2598.750000,11.5000,70.000000,1.00000
50%,17.500000,7.000000,280.00000,3381.000000,13.7500,70.000000,1.00000
75%,22.000000,8.000000,357.75000,4195.250000,15.5000,71.000000,1.00000
max,28.000000,8.000000,455.00000,5140.000000,20.5000,71.000000,3.00000

In [60]:
auto_mpg.corr()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000