## sort_values()
- sort a dataframe or series by the value along a specific axis

In [12]:
import pandas as pd
data={'Name':['Alice','Bob','Charlie','David'],'Score':[88,92,95,90]}
df=pd.DataFrame(data)
df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     95
3    David     90

In [3]:
sorted_df=df.sort_values(by='Score')
sorted_df

      Name  Score
0    Alice     88
3    David     90
1      Bob     92
2  Charlie     95

In [4]:
sorted_df=df.sort_values(by='Score',ascending=False)
sorted_df

      Name  Score
2  Charlie     95
1      Bob     92
3    David     90
0    Alice     88

## sort_index()

In [6]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     95
1      Bob     92
0    Alice     88

In [13]:
df.set_index('Name',inplace=True)
df

         Score
Name
Alice       88
Bob         92
Charlie     95
David       90

In [14]:
df.sort_index(ascending=False)

         Score
Name
David       90
Charlie     95
Bob         92
Alice       88

## apply()
- used to apply a function along an axis of a DataFrame or to the value of Series

In [28]:
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return 'pass' if x>=50 else 'Fail'
result=s.apply(pass_fail)
print(result)

0    Fail
1    pass
2    pass
3    Fail
dtype: object

In [40]:
df=pd.DataFrame({
    'physics':[60,70,80],
    'chemistry':[65,75,85],
    'Maths':[70,80,90]
})
result=df.apply(sum)# default axis=0
print(result)

physics      210
chemistry    225
Maths        240
dtype: int64

In [37]:
df=pd.DataFrame({
    'physics':[60,70,80],
    'chemistry':[65,75,85],
    'Maths':[70,80,90]
})
result=df.apply(sum,axis=1)#column wise add
print(result)

0    195
1    225
2    255
dtype: int64

In [30]:
df=pd.DataFrame({
    'physics':[60,70,80],
    'chemistry':[65,75,85],
    'Maths':[70,80,90]
})
result=df.apply(lambda x:x.mean())
print(result)

physics      70.0
chemistry    75.0
Maths        80.0
dtype: float64

In [31]:
def grade(total):
    if total>=250:
        return 'A'
    elif total>=200:
        return 'B'
    else:
        return 'C'
df['total']=df.apply(lambda x:x.sum(),axis=1)
df

   physics  chemistry  Maths  total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [32]:
df['grade']=df['total'].apply(grade)
df
# raw=True(function will give data in numpy array object)
# raw=False(function will give data in form of series)

   physics  chemistry  Maths  total grade
0       60         65     70    195     C
1       70         75     80    225     B
2       80         85     90    255     A

In [42]:
def analyze_score(row):
    total=row.sum()
    status='pass' if total>210 else 'fail'
    return [total,status]
df.apply(analyze_score,axis=1,result_type='expand')

     0     1
0  195  fail
1  225  pass
2  255  pass

In [43]:
def analyze_score(row):
    total=row.sum()
    status='pass' if total>210 else 'fail'
    return [total,status]
df.apply(analyze_score,axis=1)

0    [195, fail]
1    [225, pass]
2    [255, pass]
dtype: object

In [44]:
def analyze_score(row):
    total=row.sum()
    status='pass' if total>210 else 'fail'
    return [total,status]
df.apply(analyze_score,axis=1,result_type='reduce')

0    [195, fail]
1    [225, pass]
2    [255, pass]
dtype: object

In [45]:
df=pd.DataFrame(
{'x':[10,20,30],
 'y':[15,25,35],
 'z':[20,30,40]
})
result=df.apply(lambda x:x-x.mean(),result_type='broadcast')
print(result)

    x   y   z
0 -10 -10 -10
1   0   0   0
2  10  10  10

In [46]:
def odd_values(x,y,z):
    return x+y+z
df=pd.DataFrame({
    'A':[1,2],
    'B':[10,20]
})
df

   A   B
0  1  10
1  2  20

In [47]:
df1=df.apply(odd_values,args=(1,2))
df1

   A   B
0  4  13
1  5  23

In [48]:
def odd_values(x,m):
    return x*m
df=pd.DataFrame({
    'A':[1,2],
    'B':[10,20]
})
df

   A   B
0  1  10
1  2  20

In [49]:
df1=df.apply(odd_values,m=10)
df1

    A    B
0  10  100
1  20  200

## astype()

In [50]:
df=pd.DataFrame({
    'A':['1','2','3'],
    'B':['4','5','6']
})
print(df.dtypes)

A    object
B    object
dtype: object

In [51]:
df['A']=df['A'].astype(int)
print(df.dtypes)

A     int32
B    object
dtype: object

## replace()

In [52]:
# df.replace(to_replace,value,inplace)
df=pd.DataFrame({
    'Marks':[80,85,0,90],
    'Attendance':[75,80,0,85],
    'Grade':["A","B","F","A"]
})
result=df.replace(0,60)
print(result)

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [53]:
result1=df.replace([80,75],[90,80])
print(result1)

   Marks  Attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A

In [55]:
df["Marks"]=df["Marks"].replace(0,60)
df

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     60           0     F
3     90          85     A

## concat function
- used to combine or stack multiple series or dataframe along a specific axis(row or column)

In [56]:
df1=pd.DataFrame({
    'A':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "A":[5,6],
    "C":[7,8]
})
result=pd.concat([df1,df2],axis=0)
print(result)

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [57]:
df1=pd.DataFrame({
    'A':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "A":[5,6],
    "C":[7,8]
})
result=pd.concat([df1,df2],axis=1)
print(result)

   A  B  A  C
0  1  3  5  7
1  2  4  6  8

In [58]:
df1=pd.DataFrame({
    'A':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "A":[5,6],
    "C":[7,8]
})
result=pd.concat([df1,df2],join='outer')
print(result)

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [59]:
df1=pd.DataFrame({
    'A':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "A":[5,6],
    "C":[7,8]
})
result=pd.concat([df1,df2],join='inner')
print(result)

   A
0  1
1  2
0  5
1  6

In [60]:
df1=pd.DataFrame({
    'A':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "A":[5,6],
    "C":[7,8]
})
result=pd.concat([df1,df2],join='outer',ignore_index=True)
print(result)

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0

In [61]:
df1=pd.DataFrame({
    'E':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "C":[5,6],
    "D":[7,8]
})
result=pd.concat([df1,df2],sort=False)
print(result)

     E    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [63]:
df1=pd.DataFrame({
    'E':[1,2],
    "B":[3,4]
})
df2=pd.DataFrame({
    "C":[5,6],
    "D":[7,8]
})
result=pd.concat([df1,df2],sort=True)
print(result)

     B    C    D    E
0  3.0  NaN  NaN  1.0
1  4.0  NaN  NaN  2.0
0  NaN  5.0  7.0  NaN
1  NaN  6.0  8.0  NaN

## merge()
- pd.merge(left,right,how='inner',on,left_on,right_on)

In [65]:
df1=pd.DataFrame({
    'Employee':['A','B','C'],
    'Department':['IT','HR','Finance']
})
df2=pd.DataFrame({
    'Employee':['A','B','D'],
    'Salary':[50000,40000,30000]
})
result=pd.merge(df1,df2,on='Employee',how='outer')
result

  Employee Department   Salary
0        A         IT  50000.0
1        B         HR  40000.0
2        C    Finance      NaN
3        D        NaN  30000.0

In [66]:
df1=pd.DataFrame({
    'Employee':['A','B','C'],
    'Department':['IT','HR','Finance']
})
df2=pd.DataFrame({
    'Employee':['A','B','D'],
    'Salary':[50000,40000,30000]
})
result=pd.merge(df1,df2,on='Employee',how='inner')
result

  Employee Department  Salary
0        A         IT   50000
1        B         HR   40000

In [67]:
df1=pd.DataFrame({
    'Employee':['A','B','C'],
    'Department':['IT','HR','Finance']
})
df2=pd.DataFrame({
    'Employee':['A','B','D'],
    'Salary':[50000,40000,30000]
})
result=pd.merge(df1,df2,on='Employee',how='left')
result

  Employee Department   Salary
0        A         IT  50000.0
1        B         HR  40000.0
2        C    Finance      NaN

In [68]:
df1=pd.DataFrame({
    'Employee':['A','B','C'],
    'Department':['IT','HR','Finance']
})
df2=pd.DataFrame({
    'Employee':['A','B','D'],
    'Salary':[50000,40000,30000]
})
result=pd.merge(df1,df2,on='Employee',how='right')
result

  Employee Department  Salary
0        A         IT   50000
1        B         HR   40000
2        D        NaN   30000

In [69]:
df1=pd.DataFrame({
    "Emp_ID":[101,102,103],
    "Name":['Amit','Riya','John'],
    "Salary":[50000,60000,55000]
})
df2=pd.DataFrame({
    "Emp_ID":[101,102,104],
    "Name":["Amit","Riya","David"],
    "Salary":[52000,62000,58000]
})
result=pd.merge(df1,df2,on="Emp_ID",suffixes=('_left','_right'))
result

   Emp_ID Name_left  Salary_left Name_right  Salary_right
0     101      Amit        50000       Amit         52000
1     102      Riya        60000       Riya         62000

In [70]:
result=pd.merge(df1,df2,on="Emp_ID",suffixes=('_left','_right'),how='outer')
result

   Emp_ID Name_left  Salary_left Name_right  Salary_right
0     101      Amit      50000.0       Amit       52000.0
1     102      Riya      60000.0       Riya       62000.0
2     103      John      55000.0        NaN           NaN
3     104       NaN          NaN      David       58000.0