## Pandas

- library used for working with datasets
- it has functions for analyzing,cleaning,exploring & manipulating the data
- Pandas =>Panel Data,Python data analysis
- created by WesMckinney=>2008
- allows us to analyze big data and make conclusions based on statistical theories
- pandas can clean messy datasets and make them readable and relevant which is very important in data science

### Pandas Series
- pandas series is like a column in a table 
- it is a 1D array holding data of any type

In [3]:
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)
print(type(myvar))
print(myvar[1])

0    1
1    7
2    2
dtype: int64
<class 'pandas.core.series.Series'>
7

In [6]:
# for customize index
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a,index=['x','y','z'])
print(myvar)
print(myvar[1])

x    1
y    7
z    2
dtype: int64
7

In [8]:
a=[1.4,7,2]
myvar=pd.Series(a)
print(myvar)

0    1.4
1    7.0
2    2.0
dtype: float64

In [2]:
import pandas as pd
student_name=['ram','shyam','seeta','geeta']
marks=[60,70,80,90]
myvar=pd.Series(marks,index=student_name,name='student_result')
print(myvar)

ram      60
shyam    70
seeta    80
geeta    90
Name: student_result, dtype: int64

In [5]:
calories={'day1':400,'day2':380,'day3':480,'day4':370}
myvar=pd.Series(calories,name="Calories burn per day")
print(myvar)

day1    400
day2    380
day3    480
day4    370
Name: Calories burn per day, dtype: int64

In [12]:
calories={'day1':400,'day2':380,'day3':480,'day4':370}
myvar=pd.Series(calories,name="Calories burn per day",index=['day1','day2'])
print(myvar)

day1    400
day2    380
Name: Calories burn per day, dtype: int64

### Series Attributes

In [17]:
calories={'day1':400,'day2':380,'day3':480,'day4':370}
myvar=pd.Series(calories,name="Calories burn per day")
print(myvar.size)
print(myvar.dtype)
print(myvar.name)
print(myvar.index)
print(myvar.values)
print(myvar.is_unique)
print(myvar)

4
int64
Calories burn per day
Index(['day1', 'day2', 'day3', 'day4'], dtype='object')
[400 380 480 370]
True

In [23]:
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [24]:
subs=pd.read_csv('subs.csv',squeeze=True)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [25]:
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [26]:
subs.min()

33

In [27]:
subs.max()

396

In [28]:
subs.median()

123.0

In [29]:
subs.sum()

49510

In [32]:
subs[subs>200].size

59

In [35]:
print(subs[subs==subs.max()].index)

Int64Index([330], dtype='int64')

In [38]:
bw=pd.read_csv('bollywood.csv',index_col='movie',squeeze=True)
bw

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [39]:
bw.describe()

count             1500
unique             566
top       Akshay Kumar
freq                48
Name: lead, dtype: object

In [40]:
bw.head()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [41]:
bw.head(10)

movie
Uri: The Surgical Strike                       Vicky Kaushal
Battalion 609                                    Vicky Ahuja
The Accidental Prime Minister (film)             Anupam Kher
Why Cheat India                                Emraan Hashmi
Evening Shadows                             Mona Ambegaonkar
Soni (film)                             Geetika Vidya Ohlyan
Fraud Saiyaan                                   Arshad Warsi
Bombairiya                                      Radhika Apte
Manikarnika: The Queen of Jhansi              Kangana Ranaut
Thackeray (film)                         Nawazuddin Siddiqui
Name: lead, dtype: object

In [42]:
bw.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [43]:
bw.tail(3)

movie
Saathiya (film)         Vivek Oberoi
Company (film)            Ajay Devgn
Awara Paagal Deewana    Akshay Kumar
Name: lead, dtype: object

In [44]:
bw[0]

'Vicky Kaushal'

In [45]:
bw[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [46]:
bw[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [47]:
bw[[0,1,3,5,7]]

movie
Uri: The Surgical Strike           Vicky Kaushal
Battalion 609                        Vicky Ahuja
Why Cheat India                    Emraan Hashmi
Soni (film)                 Geetika Vidya Ohlyan
Bombairiya                          Radhika Apte
Name: lead, dtype: object

In [50]:
'2 states (2014 film)'in bw

False

In [51]:
'Alia Bhatt'in bw.values

True

In [52]:
bw.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [60]:
bw.value_counts()

Akshay Kumar          48
Amitabh Bachchan      45
Ajay Devgn            38
Salman Khan           31
Sanjay Dutt           26
                      ..
Raj Arjun              1
Shashank Udapurkar     1
Rahul Jaiswal          1
Charanpreet Insan      1
Rakesh Bedi            1
Name: lead, Length: 566, dtype: int64

In [55]:
bw.value_counts(ascending=True)

Rakesh Bedi            1
Charanpreet Insan      1
Rahul Jaiswal          1
Shashank Udapurkar     1
Raj Arjun              1
                      ..
Sanjay Dutt           26
Salman Khan           31
Ajay Devgn            38
Amitabh Bachchan      45
Akshay Kumar          48
Name: lead, Length: 566, dtype: int64

In [66]:
num_movie=bw.value_counts()
num_movie[num_movie>20]

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64

In [76]:
marks={"ram":55,"shyam":60,"seeta":65,"geeta":70}
marks_series=pd.Series(marks,name="student_result")
print(list(marks_series))
print(dict(marks_series))
marks_series[1]=100
print("--------------------------------------")
print(marks_series)
print("--------------------------------------")
print(100+marks_series)
print("--------------------------------------")
print(marks_series>=100)

[55, 60, 65, 70]
{'ram': 55, 'shyam': 60, 'seeta': 65, 'geeta': 70}
--------------------------------------
ram       55
shyam    100
seeta     65
geeta     70
Name: student_result, dtype: int64
--------------------------------------
ram      155
shyam    200
seeta    165
geeta    170
Name: student_result, dtype: int64
--------------------------------------
ram      False
shyam     True
seeta    False
geeta    False
Name: student_result, dtype: bool

In [83]:
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])
print(a+b)

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [78]:
print(a-b)

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [79]:
print(a*b)

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [80]:
print(a/b)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [81]:
print(a==b)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [85]:
print(a<b)
print("--------------------------------------")
print(a>b)

0    False
1    False
2    False
3    False
4    False
dtype: bool
--------------------------------------
0    True
1    True
2    True
3    True
4    True
dtype: bool

## DataFrame
- DataFrame is a 2 dimensional data structure like a 2D Array or table with rows and columns

In [87]:
data={"calories":[420,380,400,370],"duration":[50,40,45,35]}
df=pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       400        45
3       370        35

In [88]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [89]:
print(df['calories'])

0    420
1    380
2    400
3    370
Name: calories, dtype: int64

In [90]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40

In [96]:
data={"calories":[420,380,400,370],"duration":[50,40,45,35]}
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])
print(df)
print("--------------------------------------")
print(df.loc['day1'])
print(df.iloc['day1'])

      calories  duration
day1       420        50
day2       380        40
day3       400        45
day4       370        35
--------------------------------------
calories    420
duration     50
Name: day1, dtype: int64

TypeError: Cannot index by location index with a non-integer key

In [97]:
print(df[::2])

      calories  duration
day1       420        50
day3       400        45

In [100]:
data={"Name":["Alice","Bob","Charlie"],"Age":[25,30,35],"City":["New York","Los Angeles","Chicago"]}
df=pd.DataFrame(data)
print(df)
print("--------------------------------------")
print(df.loc[0:1])
print("--------------------------------------")
print(df.iloc[0:1])
print("--------------------------------------")
print(df.loc[(df.Age>26)])

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
--------------------------------------
    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles
--------------------------------------
    Name  Age      City
0  Alice   25  New York
--------------------------------------
      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [101]:
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data,index=['r1','r2','r3','r4'])
df

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [102]:
df.loc['r2':'r4','B']=99
df

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [104]:
df.iloc[1:3,0]=0
df

    A   B
r1  1   5
r2  0  99
r3  0  99
r4  4  99

In [109]:
df['C']=[10,20,30,40]
df

    A   B   c   C
r1  1   5  10  10
r2  0  99  20  20
r3  0  99  30  30
r4  4  99  40  40

In [110]:
df.loc[df['A']==0,'New_col']='Zero'
df

    A   B   c   C New_col
r1  1   5  10  10     NaN
r2  0  99  20  20    Zero
r3  0  99  30  30    Zero
r4  4  99  40  40     NaN

In [116]:
df.loc[len(df)]=['John',35,50,25,'zero']
df

       A   B   c   C New_col
r1     1   5  10  10     NaN
r2     0  99  20  20    Zero
r3     0  99  30  30    Zero
r4     4  99  40  40     NaN
4   John  35  50  25    zero

In [117]:
df.index

Index(['r1', 'r2', 'r3', 'r4', 4], dtype='object')

In [118]:
df.columns

Index(['A', 'B', 'c', 'C', 'New_col'], dtype='object')

In [119]:
df.size

25

In [120]:
df.values

array([[1, 5, 10, 10, nan],
       [0, 99, 20, 20, 'Zero'],
       [0, 99, 30, 30, 'Zero'],
       [4, 99, 40, 40, nan],
       ['John', 35, 50, 25, 'zero']], dtype=object)

In [121]:
df.dtypes

A          object
B           int64
c           int64
C           int64
New_col    object
dtype: object