In [4]:
import pandas as pd
df1=pd.DataFrame({
    'Student_ID':[1,2,3],
    'Name':['Amit','Riya','John']
})
df2=pd.DataFrame({
    '1D':[1,2,4],
    'Marks':[85,90,75]
})
result=pd.merge(df1,df2,left_on="Student_ID",right_on="1D")
print(result)

   Student_ID  Name  1D  Marks
0           1  Amit   1     85
1           2  Riya   2     90

In [5]:
import pandas as pd
df1=pd.DataFrame({
    'Student_ID':[1,2,3],
    'Name':['Amit','Riya','John']
})
df2=pd.DataFrame({
    '1D':[1,2,4],
    'Marks':[85,90,75]
})
result=pd.merge(df1,df2,left_on="Student_ID",right_on="1D",how="outer")
print(result)

   Student_ID  Name   1D  Marks
0         1.0  Amit  1.0   85.0
1         2.0  Riya  2.0   90.0
2         3.0  John  NaN    NaN
3         NaN   NaN  4.0   75.0

In [7]:
df1=pd.DataFrame({
    'Physics':[60,70,80]},index=[101,102,103])
df2=pd.DataFrame({'Name':['Alice','Bob','Charlie']},index=[101,102,103])
result=pd.merge(df1,df2,left_index=True,right_index=True)
print(result)

     Physics     Name
101       60    Alice
102       70      Bob
103       80  Charlie

In [8]:
import pandas as pd
df1=pd.DataFrame({
    'Student_ID':[1,2,3],
    'Name':['Amit','Riya','John']
})
df2=pd.DataFrame({
    'Marks':[85,90,75]
},index=[1,2,3])
result=pd.merge(df1,df2,left_on="Student_ID",right_index=True)
print(result)

   Student_ID  Name  Marks
0           1  Amit     85
1           2  Riya     90
2           3  John     75

## groupby()
- used to split a DataFrame into groups based on one or more columns,allowing for efficient data analysis and aggregation

In [9]:
data={'Product Category':['Electronics','Furniture','Electronics','Furniture'],
     'Sales':[200,150,300,100]}
df=pd.DataFrame(data)
df

  Product Category  Sales
0      Electronics    200
1        Furniture    150
2      Electronics    300
3        Furniture    100

In [14]:
result=df.groupby('Product Category')['Sales'].sum()
print(result)

Product Category
Electronics    500
Furniture      250
Name: Sales, dtype: int64

In [15]:
result=df.groupby('Product Category')['Sales'].mean()
print(result)

Product Category
Electronics    250.0
Furniture      125.0
Name: Sales, dtype: float64

In [16]:
result=df.groupby('Product Category')['Sales'].median()
print(result)

Product Category
Electronics    250.0
Furniture      125.0
Name: Sales, dtype: float64

In [18]:
result=df.groupby('Product Category',as_index=True).count()#default value True
print(result)

                  Sales
Product Category
Electronics           2
Furniture             2

In [19]:
result=df.groupby('Product Category',as_index=False).count()
print(result)

  Product Category  Sales
0      Electronics      2
1        Furniture      2

In [20]:
result=df.groupby('Product Category')['Sales'].describe()
print(result)

                  count   mean        std    min    25%    50%    75%    max
Product Category
Electronics         2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Furniture           2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [23]:
result=df.groupby('Product Category')['Sales'].sample()
print(result)

2    300
1    150
Name: Sales, dtype: int64

In [24]:
result=df.groupby('Product Category')['Sales'].size()
print(result)

Product Category
Electronics    2
Furniture      2
Name: Sales, dtype: int64

In [25]:
result=df.groupby('Product Category')['Sales'].count()
print(result)

Product Category
Electronics    2
Furniture      2
Name: Sales, dtype: int64

In [26]:
result=df.groupby('Product Category')['Sales'].nth(0)
print(result)

0    200
1    150
Name: Sales, dtype: int64

In [27]:
result=df.groupby('Product Category')['Sales'].nth(1)
print(result)

2    300
3    100
Name: Sales, dtype: int64

In [28]:
result=df.groupby('Product Category')['Sales'].groups
print(result)

{'Electronics': [0, 2], 'Furniture': [1, 3]}

In [30]:
result=df.groupby('Product Category')['Sales'].nunique()
print(result)

Product Category
Electronics    2
Furniture      2
Name: Sales, dtype: int64

In [33]:
df=pd.DataFrame({
    'Department':['Sales','Sales','HR','HR','IT','IT'],
    'Salary':[50000,60000,40000,45000,70000,75000],
    'Bonus':[5000,6000,2000,2500,8000,8500]
})
result=df.groupby('Department').agg({'Salary':['mean','max'],'Bonus':'sum'})
print(result)

             Salary         Bonus
               mean    max    sum
Department
HR          42500.0  45000   4500
IT          72500.0  75000  16500
Sales       55000.0  60000  11000

In [34]:
result=df.groupby('Department').agg('mean')
print(result)

             Salary   Bonus
Department
HR          42500.0  2250.0
IT          72500.0  8250.0
Sales       55000.0  5500.0

In [35]:
result=df.groupby('Department').agg(['mean','min','max'])
print(result)

             Salary                 Bonus
               mean    min    max    mean   min   max
Department
HR          42500.0  40000  45000  2250.0  2000  2500
IT          72500.0  70000  75000  8250.0  8000  8500
Sales       55000.0  50000  60000  5500.0  5000  6000

In [37]:
result=df.groupby('Department').agg(MeanSalary=('Salary','mean'),MaxSalary=('Salary','max'),TotalBonus=('Bonus','sum'))
print(result)

            MeanSalary  MaxSalary  TotalBonus
Department
HR             42500.0      45000        4500
IT             72500.0      75000       16500
Sales          55000.0      60000       11000

In [38]:
df=pd.DataFrame({
    'Region':['East','East','West','West','East','West'],
    'Sales':[100,150,200,120,110,130],
    'Manager':['A','B','C','D','E','F']
})
df

  Region  Sales Manager
0   East    100       A
1   East    150       B
2   West    200       C
3   West    120       D
4   East    110       E
5   West    130       F